// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy1StdFS6YrpgRvSGJzRDuSE4NvC95TWA',
    appId: '1:79606237302:web:56f15ead6d6a1699a77757',
    messagingSenderId: '79606237302',
    projectId: 'chat-application-1346c',
    authDomain: 'chat-application-1346c.firebaseapp.com',
    storageBucket: 'chat-application-1346c.firebasestorage.app',
    measurementId: 'G-63WX0TNDQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf39g6uUannp4vwg5QHK83-1dTN53S3aQ',
    appId: '1:79606237302:android:e9450d2c27955fcea77757',
    messagingSenderId: '79606237302',
    projectId: 'chat-application-1346c',
    storageBucket: 'chat-application-1346c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBffTN_JEVuMxcmJ9Qu1UsDpqbB9IGfQ0',
    appId: '1:79606237302:ios:4bad2f07f56031fca77757',
    messagingSenderId: '79606237302',
    projectId: 'chat-application-1346c',
    storageBucket: 'chat-application-1346c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBffTN_JEVuMxcmJ9Qu1UsDpqbB9IGfQ0',
    appId: '1:79606237302:ios:4bad2f07f56031fca77757',
    messagingSenderId: '79606237302',
    projectId: 'chat-application-1346c',
    storageBucket: 'chat-application-1346c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
